CREATE TABLE IF NOT EXISTS Artist (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL, 
    image TEXT NOT NULL,
    popularity INT NOT NULL,
    country VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS Song (
    id SERIAL PRIMARY KEY,
    artist_id INT NOT NULL REFERENCES Artist(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    image TEXT NOT NULL,
    year INT NOT NULL,
    popularity INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Mood (
    type VARCHAR(50) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Genre (
    name VARCHAR(100) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Song_moods (
    mood_type VARCHAR(50) NOT NULL REFERENCES Mood(type) ON DELETE CASCADE,
    song_id INT NOT NULL REFERENCES Song(id) ON DELETE CASCADE,
    PRIMARY KEY (mood_type, song_id)
);

CREATE TABLE IF NOT EXISTS Song_genres (
    genre_name VARCHAR(100) NOT NULL REFERENCES Genre(name) ON DELETE CASCADE,
    song_id INT NOT NULL REFERENCES Song(id) ON DELETE CASCADE,
    PRIMARY KEY (genre_name, song_id)
);
